version: 2.9

builds:
  - binary: kasmos
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: kastheco
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    name: kasmos
    homepage: "https://github.com/kastheco/kasmos"
    description: "kas - A TUI-based agent-driven IDE for managing multiple AI agents"
    license: "AGPL-3.0"
    install: |
      bin.install "kasmos"
    test: |
      system "#{bin}/kasmos", "version"

scoops:
  - repository:
      owner: kastheco
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"
    name: kasmos
    homepage: "https://github.com/kastheco/kasmos"
    description: "kas - A TUI-based agent-driven IDE for managing multiple AI agents"
    license: AGPL-3.0

release:
  prerelease: auto
  draft: true
  replace_existing_draft: true

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github

  filters:
    exclude:
      - "^docs:"
      - typo
      - "^refactor"
      - "^chore"
