version: 2

builds:
  - binary: kasmos
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

homebrew_casks:
  - repository:
      owner: kastheco
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    name: kasmos
    homepage: "https://github.com/kastheco/kasmos"
    description: "kas - A TUI-based agent-driven IDE for managing multiple AI agents"
    license: "AGPL-3.0"
    binaries:
      - kasmos

release:
  prerelease: auto
  draft: false

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github

  filters:
    exclude:
      - "^docs:"
      - typo
      - "^refactor"
      - "^chore"
