name: Build

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: Build Binary and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Run tests
      run: go test -v ./...

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -v -o build/${{ matrix.goos }}_${{ matrix.goarch }}/kasmos

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kasmos-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/${{ matrix.goos }}_${{ matrix.goarch }}/*
        retention-days: 7
